apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavacl-rc
spec:
  replicas: 5
  selector:
    app: myjava

  template:
    metadata:
      labels:
        app: myjava
        
    spec:
      containers:
      - name: myjava
        image: sankar9063/myjava30oct:1
        ports:
        - containerPort: 8080