apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavacl-rc
spec:
  replicas: 5
  selector:
    app: myjava
    version: 2.1.5

  template:
    metadata:
      labels:
        app: myjava
        version: 2.1.5
        
    spec:
      containers:
      - name: myjava
        image: sankar9063/myjava30oct:2
        ports:
        - containerPort: 8080