apiVersion: v1
kind: Service
metadata:
  name: san-svc
  labels:
    app: myjava
  
  
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjava
  